project:
  type: website
  output-dir: docs

website:
  title: "MLEM convergence proofs"
  navbar:
    left:
      - text: "MLEM-FB full rank"
        href: index.qmd
      - text: "logL demo"
        href: logL_interactive.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



